name: 'json_dynamic_widget_annotations'
description: 'Annotations for the json_dynamic_widget library.'
homepage: 'https://github.com/peiffer-innovations/json_dynamic_widget_annotations'
version: '1.0.0+10'

environment: 
  sdk: '>=3.0.0 <4.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'
    - 'lib/**/*.g.dart'

dev_dependencies: 
  flutter_lints: '^3.0.1'
  test: '^1.25.2'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
